"""
Auto-generated NovaSight DAG
============================

DAG ID: novasight-demo_extract_gl_data_pipeline
Version: 3
Generated: 2026-02-16T12:17:21.484842
Owner: novasight

WARNING: This file is auto-generated by NovaSight.
Do not edit manually - changes will be overwritten.

Spark submission: Uses native SparkSubmitOperator (preferred) or docker exec fallback.
"""
from __future__ import annotations

import os
from datetime import datetime, timedelta
import pendulum
from airflow.models.dag import DAG
from airflow.providers.standard.operators.empty import EmptyOperator
from airflow.providers.standard.operators.python import PythonOperator
from airflow.providers.standard.operators.bash import BashOperator
from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
from airflow.providers.smtp.operators.smtp import EmailOperator
from airflow.providers.http.sensors.http import HttpSensor
from airflow.providers.standard.sensors.time import TimeSensor
from airflow.task.trigger_rule import TriggerRule

# ============================================
# Spark Configuration
# ============================================
SPARK_HOME = os.environ.get('SPARK_HOME', '/opt/spark')
SPARK_MASTER = os.environ.get('SPARK_MASTER', 'spark://spark-master:7077')
SPARK_MASTER_CONTAINER = os.environ.get('SPARK_MASTER_CONTAINER', 'novasight-spark-master')

# Check if native Spark is available (preferred)
SPARK_NATIVE_AVAILABLE = os.path.exists(f'{SPARK_HOME}/bin/spark-submit')


# Default arguments for all tasks
default_args = {
    'owner': 'novasight',
    'depends_on_past': False,
    'retries': 1,
    'retry_delay': timedelta(minutes=5),
    'email_on_failure': False,
    'email_on_success': False,
}

# DAG Definition
with DAG(
    dag_id='novasight-demo_extract_gl_data_pipeline',
    description='Data pipeline for extract_gl_data - extracting from GL_DATA to stg_doc_data',
    default_args=default_args,
    schedule=None,
    start_date=pendulum.datetime(2024, 1, 1, tz='UTC'),
    catchup=False,
    max_active_runs=1,
    tags=["novasight-demo", "novasight-demo", "novasight-demo", "pyspark", "etl"],
) as dag:
    
    # Start task
    start = EmptyOperator(task_id='start')
    
    # End task
    end = EmptyOperator(task_id='end')
    
    # Task definitions
    tasks = {}
    
    # Task: extract_gl_data_task
    # Use native SparkSubmitOperator (preferred)
    tasks['extract_gl_data_task'] = SparkSubmitOperator(
        task_id='extract_gl_data_task',
        application='/opt/spark/jobs/extract_gl_data.py',
        conn_id='spark_default',
        executor_memory='2g',
        executor_cores=2,
        driver_memory='1g',
        conf={
            'spark.executor.memory': '2g',
            'spark.executor.cores': '2',
        },
        execution_timeout=timedelta(minutes=60),
        retries=1,
        retry_delay=timedelta(minutes=5),
        trigger_rule=TriggerRule.ALL_SUCCESS,
    )
    

# ============================================
# Task Dependencies
# ============================================
# Dependencies are set at the end after all tasks are defined
# to ensure proper resolution regardless of conditional task creation

# Connect start to all root tasks (tasks with no dependencies)
start >> [tasks['extract_gl_data_task']]

# Define explicit task dependencies

# Connect all leaf tasks (tasks that nothing depends on) to end
[tasks['extract_gl_data_task']] >> end
