"""
NovaSight Pydantic Schemas
==========================

Request/Response validation schemas.
"""

from app.schemas.auth_schemas import LoginRequest, TokenResponse
from app.schemas.dag_schemas import (
    DagConfigCreate,
    DagConfigUpdate,
    TaskConfigCreate,
    DagConfigResponse,
)
from app.schemas.connection_schemas import (
    ConnectionCreateSchema,
    ConnectionUpdateSchema,
    ConnectionTestSchema,
    ConnectionResponseSchema,
    ConnectionTestResultSchema,
    ConnectionListQuerySchema,
    ConnectionListResponseSchema,
    SchemaResponseSchema,
    TableSchema,
    ColumnSchema,
)
from app.schemas.pyspark_schemas import (
    PySparkAppCreateSchema,
    PySparkAppUpdateSchema,
    PySparkAppResponseSchema,
    PySparkAppWithCodeSchema,
    PySparkAppListQuerySchema,
    PySparkAppListResponseSchema,
    PySparkCodePreviewSchema,
    PySparkCodeResponseSchema,
    QueryValidationRequestSchema,
    QueryValidationResponseSchema,
    ColumnConfigSchema,
    SourceTypeEnum,
    WriteModeEnum,
    SCDTypeEnum,
    CDCTypeEnum,
    PySparkAppStatusEnum,
)
from app.schemas.dbt_schemas import (
    DbtRunRequest,
    DbtTestRequest,
    DbtBuildRequest,
    DbtCompileRequest,
    DbtSeedRequest,
    DbtSnapshotRequest,
    DbtListRequest,
    DbtResultResponse,
    DbtLineageResponse,
    ModelDefinition,
    ColumnDefinition as DbtColumnDefinition,
    JoinDefinition,
    Materialization,
    JoinType,
    TestType,
)
from app.schemas.semantic_schemas import (
    SemanticModelCreateSchema,
    SemanticModelUpdateSchema,
    SemanticModelResponseSchema,
    DimensionCreateSchema,
    DimensionUpdateSchema,
    DimensionResponseSchema,
    MeasureCreateSchema,
    MeasureUpdateSchema,
    MeasureResponseSchema,
    RelationshipCreateSchema,
    RelationshipResponseSchema,
    SemanticQuerySchema,
    QueryResultSchema,
    FilterSchema,
    OrderBySchema,
    DimensionTypeEnum,
    AggregationTypeEnum,
    ModelTypeEnum,
    RelationshipTypeEnum,
    JoinTypeEnum,
    FilterOperatorEnum,
    SortOrderEnum,
)

__all__ = [
    "LoginRequest",
    "TokenResponse",
    "DagConfigCreate",
    "DagConfigUpdate",
    "TaskConfigCreate",
    "DagConfigResponse",
    "ConnectionCreateSchema",
    "ConnectionUpdateSchema",
    "ConnectionTestSchema",
    "ConnectionResponseSchema",
    "ConnectionTestResultSchema",
    "ConnectionListQuerySchema",
    "ConnectionListResponseSchema",
    "SchemaResponseSchema",
    "TableSchema",
    "ColumnSchema",
    # PySpark schemas
    "PySparkAppCreateSchema",
    "PySparkAppUpdateSchema",
    "PySparkAppResponseSchema",
    "PySparkAppWithCodeSchema",
    "PySparkAppListQuerySchema",
    "PySparkAppListResponseSchema",
    "PySparkCodePreviewSchema",
    "PySparkCodeResponseSchema",
    "QueryValidationRequestSchema",
    "QueryValidationResponseSchema",
    "ColumnConfigSchema",
    "SourceTypeEnum",
    "WriteModeEnum",
    "SCDTypeEnum",
    "CDCTypeEnum",
    "PySparkAppStatusEnum",
    # dbt schemas
    "DbtRunRequest",
    "DbtTestRequest",
    "DbtBuildRequest",
    "DbtCompileRequest",
    "DbtSeedRequest",
    "DbtSnapshotRequest",
    "DbtListRequest",
    "DbtResultResponse",
    "DbtLineageResponse",
    "ModelDefinition",
    "DbtColumnDefinition",
    "JoinDefinition",
    "Materialization",
    "JoinType",
    "TestType",
    # Semantic layer schemas
    "SemanticModelCreateSchema",
    "SemanticModelUpdateSchema",
    "SemanticModelResponseSchema",
    "DimensionCreateSchema",
    "DimensionUpdateSchema",
    "DimensionResponseSchema",
    "MeasureCreateSchema",
    "MeasureUpdateSchema",
    "MeasureResponseSchema",
    "RelationshipCreateSchema",
    "RelationshipResponseSchema",
    "SemanticQuerySchema",
    "QueryResultSchema",
    "FilterSchema",
    "OrderBySchema",
    "DimensionTypeEnum",
    "AggregationTypeEnum",
    "ModelTypeEnum",
    "RelationshipTypeEnum",
    "JoinTypeEnum",
    "FilterOperatorEnum",
    "SortOrderEnum",
]
