"""
PySpark Extract Job: extract_users
Generated by NovaSight Template Engine
Generated at: 2026-03-03T12:43:05.116125
Template Version: 1.0.0
App ID: c74e0e82-a563-46b5-b9a1-67d2718c1864
Tenant ID: d37ec056-17f1-473a-8788-83051a68ba27

DO NOT MODIFY THIS FILE DIRECTLY.
All changes should be made through the NovaSight UI.
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, lit, current_timestamp
from pyspark.sql.types import *
import logging
import os
from datetime import datetime

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger("extract_users")


class ExtractJob:
    """
    Extract job for extract_users.
    
    Source: postgresql - 172.22.24.7:5432/postgres
    Target: tenant_novasight_demo.stg_users
    Write Mode: overwrite
    Tenant: d37ec056-17f1-473a-8788-83051a68ba27
    
    SECURITY: This job is scoped to tenant database only.
    """
    
    # Tenant isolation constants
    TENANT_ID = "d37ec056-17f1-473a-8788-83051a68ba27"
    TENANT_DATABASE = os.getenv("TENANT_DATABASE", "tenant_novasight_demo")
    
    def __init__(self, spark: SparkSession):
        self.spark = spark
        self.app_name = "extract_users"
        self.app_id = "c74e0e82-a563-46b5-b9a1-67d2718c1864"
        self.tenant_id = self.TENANT_ID
        
        # Source configuration
        self.source_config = {
            "db_type": "postgresql",
            "host": os.getenv("SOURCE_DB_HOST", "172.22.24.7"),
            "port": int(os.getenv("SOURCE_DB_PORT", "5432")),
            "database": "postgres",
            "schema": "hrapp",
            "username": os.getenv("SOURCE_DB_USER", "postgres"),
            "password": os.getenv("SOURCE_DB_PASSWORD", "Dataw_135"),
        }
        
        # Target configuration - always use tenant database
        self.target_config = {
            "database": os.getenv("TARGET_DATABASE", self.TENANT_DATABASE),
            "table": "stg_users",
            "engine": "MergeTree",
        }
        
        # Primary key columns for ORDER BY and PRIMARY KEY in ClickHouse
        self.primary_keys = [
            "id",
            "branch",
        ]
        
        # Validate target database belongs to tenant
        self._validate_target_database()
        
        # Job configuration
        self.write_mode = "overwrite"
        self.batch_size = 10000
        
        # Column type mappings: source column -> ClickHouse type
        # Generated from source database type: postgresql
        self.column_type_mapping = {
            "id": "Int32",
            "username": "String",
            "password": "String",
            "role": "String",
            "branch": "String",
        }
        
        # Metadata column types for ClickHouse
        self.metadata_columns = {
            "_novasight_app_id": "String",
            "_novasight_extracted_at": "DateTime64(3)",
            "_novasight_tenant_id": "String",
        }
    
    def _validate_target_database(self):
        """Validate that target database belongs to this tenant."""
        import re
        target_db = self.target_config["database"]
        
        # Check if trying to access another tenant's database
        if target_db.startswith("tenant_") and target_db != self.TENANT_DATABASE:
            raise ValueError(
                f"Security violation: Cannot write to database '{target_db}'. "
                f"This job can only write to '{self.TENANT_DATABASE}'."
            )
        
    def get_jdbc_url(self) -> str:
        """Build JDBC URL based on database type."""
        db_type = self.source_config["db_type"]
        host = self.source_config["host"]
        port = self.source_config["port"]
        database = self.source_config["database"]
        
        jdbc_drivers = {
            "postgresql": f"jdbc:postgresql://{host}:{port}/{database}",
            "mysql": f"jdbc:mysql://{host}:{port}/{database}",
            "oracle": f"jdbc:oracle:thin:@{host}:{port}:{database}",
            "sqlserver": f"jdbc:sqlserver://{host}:{port};databaseName={database}",
        }
        
        return jdbc_drivers.get(db_type, f"jdbc:postgresql://{host}:{port}/{database}")
    
    def get_jdbc_driver(self) -> str:
        """Get JDBC driver class name."""
        drivers = {
            "postgresql": "org.postgresql.Driver",
            "mysql": "com.mysql.cj.jdbc.Driver",
            "oracle": "oracle.jdbc.OracleDriver",
            "sqlserver": "com.microsoft.sqlserver.jdbc.SQLServerDriver",
        }
        return drivers.get(self.source_config["db_type"], "org.postgresql.Driver")
    
    def get_clickhouse_create_table_ddl(self) -> str:
        """
        Generate CREATE TABLE DDL for ClickHouse with proper type mappings.
        
        Returns:
            CREATE TABLE DDL string
        """
        target_db = self.target_config["database"]
        target_table = self.target_config["table"]
        engine = self.target_config["engine"]
        
        # Build column definitions with mapped ClickHouse types
        # Primary key columns are NOT nullable
        column_defs = []
        for col_name, ch_type in self.column_type_mapping.items():
            if col_name in self.primary_keys:
                column_defs.append(f"    `{col_name}` {ch_type}")
            else:
                column_defs.append(f"    `{col_name}` Nullable({ch_type})")
        
        # Add metadata columns (not nullable)
        for col_name, ch_type in self.metadata_columns.items():
            column_defs.append(f"    `{col_name}` {ch_type}")
        
        columns_str = ",\n".join(column_defs)
        
        # Use primary keys for ORDER BY (required for MergeTree family)
        if self.primary_keys:
            pk_cols = ", ".join([f"`{pk}`" for pk in self.primary_keys])
            order_by_clause = f"ORDER BY ({pk_cols})"
            primary_key_clause = f"PRIMARY KEY ({pk_cols})"
        else:
            order_by_clause = "ORDER BY tuple()"
            primary_key_clause = ""
        
        partition_clause = ""
        
        ddl = f"""
CREATE TABLE IF NOT EXISTS `{target_db}`.`{target_table}`
(
{columns_str}
)
ENGINE = {engine}
{order_by_clause}
{primary_key_clause}
{partition_clause}
""".strip()
        
        return ddl
    
    def ensure_target_table(self):
        """
        Ensure the target ClickHouse table exists with correct schema.
        
        Creates the table if it doesn't exist, using the column type mappings
        derived from the source database types.
        """
        import clickhouse_connect
        
        target_url = os.getenv("CLICKHOUSE_HOST", "clickhouse")
        target_port = int(os.getenv("CLICKHOUSE_PORT", "8123"))
        target_user = os.getenv("CLICKHOUSE_USER", "default")
        target_password = os.getenv("CLICKHOUSE_PASSWORD", "")
        
        try:
            client = clickhouse_connect.get_client(
                host=target_url,
                port=target_port,
                username=target_user,
                password=target_password,
            )
            
            ddl = self.get_clickhouse_create_table_ddl()
            logger.info(f"Creating target table if not exists:\n{ddl}")
            
            client.command(ddl)
            logger.info(f"Target table ensured: {self.target_config['database']}.{self.target_config['table']}")
            
        except Exception as e:
            logger.warning(f"Could not ensure target table via DDL (will rely on JDBC auto-create): {e}")
    
    def read_source(self):
        """Read data from source database."""
        logger.info(f"Reading from source: {self.source_config['database']}")
        
        jdbc_url = self.get_jdbc_url()
        jdbc_driver = self.get_jdbc_driver()
        
        connection_props = {
            "user": self.source_config["username"],
            "password": self.source_config["password"],
            "driver": jdbc_driver,
            "fetchsize": str(self.batch_size),
        }
        
        # Read from table
        table_name = "hrapp.users"
        
        df = self.spark.read.jdbc(
            url=jdbc_url,
            table=table_name,
            properties=connection_props
        )
        
        # Select only configured columns
        selected_columns = [
            "id",
            "username",
            "password",
            "role",
            "branch",
        ]
        
        df = df.select([col(c) for c in selected_columns])
        
        logger.info(f"Read {df.count()} rows from source")
        return df
    
    def add_metadata_columns(self, df):
        """Add metadata columns for audit tracking."""
        return df \
            .withColumn("_novasight_app_id", lit(self.app_id)) \
            .withColumn("_novasight_extracted_at", current_timestamp()) \
            .withColumn("_novasight_tenant_id", lit("d37ec056-17f1-473a-8788-83051a68ba27"))
    
    
    def write_to_target(self, df):
        """Write data to ClickHouse target."""
        logger.info(f"Writing to target: {self.target_config['database']}.{self.target_config['table']}")
        
        target_url = os.getenv("CLICKHOUSE_URL", "jdbc:clickhouse://clickhouse:8123")
        target_host = os.getenv("CLICKHOUSE_HOST", "clickhouse")
        target_port = os.getenv("CLICKHOUSE_PORT", "8123")
        target_user = os.getenv("CLICKHOUSE_USER", "default")
        target_password = os.getenv("CLICKHOUSE_PASSWORD", "")
        
        connection_props = {
            "user": target_user,
            "password": target_password,
            "driver": "com.clickhouse.jdbc.ClickHouseDriver",
        }
        
        target_table = f"{self.target_config['database']}.{self.target_config['table']}"
        
        # For overwrite mode: truncate table first, then append
        # This preserves the ClickHouse DDL (ORDER BY, ENGINE, etc.)
        try:
            import urllib.request
            import urllib.parse
            truncate_sql = f"TRUNCATE TABLE IF EXISTS {target_table}"
            params = {"query": truncate_sql}
            if target_user:
                params["user"] = target_user
            if target_password:
                params["password"] = target_password
            query_string = urllib.parse.urlencode(params)
            http_url = f"http://{target_host}:{target_port}/?{query_string}"
            req = urllib.request.Request(http_url, method='POST')
            with urllib.request.urlopen(req, timeout=30) as response:
                logger.info(f"Truncated table {target_table}")
        except Exception as e:
            logger.warning(f"Could not truncate table (may not exist yet): {e}")
        
        df.write.jdbc(
            url=target_url,
            table=target_table,
            mode="append",  # Always use append; table is already created/truncated
            properties=connection_props
        )
        
        logger.info(f"Successfully wrote {df.count()} rows to target")
    
    def run(self):
        """Execute the extract job."""
        logger.info(f"Starting extract job: {self.app_name}")
        start_time = datetime.now()
        
        try:
            # Ensure target table exists with correct schema
            self.ensure_target_table()
            
            # Read source data
            df = self.read_source()
            
            # Add metadata columns
            df = self.add_metadata_columns(df)
            
            
            # Write to target
            self.write_to_target(df)
            
            duration = (datetime.now() - start_time).total_seconds()
            logger.info(f"Extract job completed in {duration:.2f} seconds")
            
            return {
                "status": "success",
                "rows_processed": df.count(),
                "duration_seconds": duration,
            }
            
        except Exception as e:
            logger.error(f"Extract job failed: {str(e)}")
            raise


def main():
    """Main entry point."""
    spark = SparkSession.builder \
        .appName("extract_users") \
        .config("spark.sql.adaptive.enabled", "true") \
        .config("spark.sql.shuffle.partitions", "200") \
        .getOrCreate()
    
    try:
        job = ExtractJob(spark)
        result = job.run()
        logger.info(f"Job result: {result}")
    finally:
        spark.stop()


if __name__ == "__main__":
    main()
