"""
PySpark SCD Type 1 Job: extract_gl_data
Generated by NovaSight Template Engine
Generated at: 2026-02-16T10:42:24.414757
Template Version: 1.0.0
App ID: f8378f02-a6f5-4090-b02d-dff9aeb75524
Tenant ID: eb09c5fc-6c5b-4745-a7ea-c3166a65de97

SCD Type 1: Overwrites existing record values with new values.
No historical tracking - only current state is maintained.

DO NOT MODIFY THIS FILE DIRECTLY.
All changes should be made through the NovaSight UI.
"""

from pyspark.sql import SparkSession, DataFrame
from pyspark.sql.functions import col, lit, current_timestamp, when, coalesce
from pyspark.sql.types import *
import logging
import os
import urllib.request
import urllib.parse
from datetime import datetime

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger("extract_gl_data")


class SCDType1Job:
    """
    SCD Type 1 job for extract_gl_data.
    
    Source: oracle - 128.1.1.3:1521/NCH
    Target: tenant_novasight_demo.stg_doc_data
    Primary Keys: DOC_ID, C_ID, DOC_NO, TP_SEQ_NO
    CDC Column: CREATION_DATE (timestamp)
    """
    
    def __init__(self, spark: SparkSession):
        self.spark = spark
        self.app_name = "extract_gl_data"
        self.app_id = "f8378f02-a6f5-4090-b02d-dff9aeb75524"
        
        # Source configuration
        self.source_config = {
            "db_type": "oracle",
            "host": os.getenv("SOURCE_DB_HOST", "128.1.1.3"),
            "port": int(os.getenv("SOURCE_DB_PORT", "1521")),
            "database": "NCH",
            "schema": "APP_ADMIN",
            "username": os.getenv("SOURCE_DB_USER", "app_admin"),
            "password": os.getenv("SOURCE_DB_PASSWORD", "Sa0509867137@"),
        }
        
        # Target configuration
        self.target_config = {
            "database": "tenant_novasight_demo",
            "table": "stg_doc_data",
            "engine": "ReplacingMergeTree",
        }
        
        # SCD configuration
        self.primary_keys = [
            "DOC_ID",
            "C_ID",
            "DOC_NO",
            "TP_SEQ_NO",
        ]
        
        # CDC configuration
        self.cdc_column = "CREATION_DATE"
        self.cdc_type = "timestamp"
        
        # Job configuration
        self.batch_size = 10000
        
        # Column type mappings: source column -> ClickHouse type
        # Generated from source database type: oracle
        self.column_type_mapping = {
            "C_ID": "Float64",
            "DOC_DATE": "DateTime",
            "DOC_ID": "Float64",
            "DOC_NO": "String",
            "TP_SEQ_NO": "Float64",
            "YEAR": "String",
            "TOTAL_LAB_PRICE": "Float64",
            "CREATION_DATE": "DateTime",
            "AMEND_LAST_DATE": "DateTime",
        }
        
        # Metadata column types for ClickHouse
        self.metadata_columns = {
            "_novasight_app_id": "String",
            "_novasight_extracted_at": "DateTime64(3)",
            "_novasight_updated_at": "DateTime64(3)",
            "_novasight_is_deleted": "UInt8",
        }
        
    def get_jdbc_url(self) -> str:
        """Build JDBC URL based on database type."""
        db_type = self.source_config["db_type"]
        host = self.source_config["host"]
        port = self.source_config["port"]
        database = self.source_config["database"]
        
        jdbc_drivers = {
            "postgresql": f"jdbc:postgresql://{host}:{port}/{database}",
            "mysql": f"jdbc:mysql://{host}:{port}/{database}",
            "oracle": f"jdbc:oracle:thin:@{host}:{port}:{database}",
            "sqlserver": f"jdbc:sqlserver://{host}:{port};databaseName={database}",
        }
        
        return jdbc_drivers.get(db_type, f"jdbc:postgresql://{host}:{port}/{database}")
    
    def get_jdbc_driver(self) -> str:
        """Get JDBC driver class name."""
        drivers = {
            "postgresql": "org.postgresql.Driver",
            "mysql": "com.mysql.cj.jdbc.Driver",
            "oracle": "oracle.jdbc.OracleDriver",
            "sqlserver": "com.microsoft.sqlserver.jdbc.SQLServerDriver",
        }
        return drivers.get(self.source_config["db_type"], "org.postgresql.Driver")
    
    def get_clickhouse_create_table_ddl(self) -> str:
        """
        Generate CREATE TABLE DDL for ClickHouse with proper type mappings.
        Uses ReplacingMergeTree engine for SCD Type 1 (to handle updates).
        
        Returns:
            CREATE TABLE DDL string
        """
        target_db = self.target_config["database"]
        target_table = self.target_config["table"]
        engine = self.target_config.get("engine", "ReplacingMergeTree")
        
        # Build column definitions with mapped ClickHouse types
        column_defs = []
        for col_name, ch_type in self.column_type_mapping.items():
            column_defs.append(f"    `{col_name}` Nullable({ch_type})")
        
        # Add metadata columns (not nullable)
        for col_name, ch_type in self.metadata_columns.items():
            column_defs.append(f"    `{col_name}` {ch_type}")
        
        columns_str = ",\n".join(column_defs)
        
        # Use primary keys for ORDER BY (required for ReplacingMergeTree)
        pk_cols = ", ".join([f"`{pk}`" for pk in self.primary_keys])
        order_by_clause = f"ORDER BY ({pk_cols})" if pk_cols else "ORDER BY tuple()"
        
        partition_clause = ""
        
        # For SCD Type 1, use ReplacingMergeTree with _novasight_updated_at as version
        ddl = f"""
CREATE TABLE IF NOT EXISTS `{target_db}`.`{target_table}`
(
{columns_str}
)
ENGINE = {engine}(_novasight_updated_at)
{order_by_clause}
{partition_clause}
""".strip()
        
        return ddl
    
    def ensure_target_table(self):
        """
        Ensure the target ClickHouse table exists with correct schema.
        
        Creates the table if it doesn't exist, using the column type mappings
        derived from the source database types.
        """
        import clickhouse_connect
        
        target_url = os.getenv("CLICKHOUSE_HOST", "localhost")
        target_port = int(os.getenv("CLICKHOUSE_PORT", "8123"))
        target_user = os.getenv("CLICKHOUSE_USER", "default")
        target_password = os.getenv("CLICKHOUSE_PASSWORD", "")
        
        try:
            client = clickhouse_connect.get_client(
                host=target_url,
                port=target_port,
                username=target_user,
                password=target_password,
            )
            
            ddl = self.get_clickhouse_create_table_ddl()
            logger.info(f"Creating target table if not exists:\n{ddl}")
            
            client.command(ddl)
            logger.info(f"Target table ensured: {self.target_config['database']}.{self.target_config['table']}")
            
        except Exception as e:
            logger.warning(f"Could not ensure target table via DDL (will rely on JDBC auto-create): {e}")
    
    def get_high_watermark(self) -> str:
        """Get high watermark from state store for CDC."""
        # In production, this would read from a state store
        watermark_file = f"/tmp/watermark_{self.app_id}.txt"
        try:
            with open(watermark_file, 'r') as f:
                return f.read().strip()
        except FileNotFoundError:
            return None
    
    def save_high_watermark(self, value: str):
        """Save high watermark to state store."""
        watermark_file = f"/tmp/watermark_{self.app_id}.txt"
        with open(watermark_file, 'w') as f:
            f.write(str(value))
        logger.info(f"Saved high watermark: {value}")
    
    def read_source(self) -> DataFrame:
        """Read data from source database with optional CDC filtering."""
        logger.info(f"Reading from source: {self.source_config['database']}")
        
        jdbc_url = self.get_jdbc_url()
        jdbc_driver = self.get_jdbc_driver()
        
        connection_props = {
            "user": self.source_config["username"],
            "password": self.source_config["password"],
            "driver": jdbc_driver,
            "fetchsize": str(self.batch_size),
        }
        
        # Table reference
        table_name = "APP_ADMIN.GL_DATA"
        base_query = f"SELECT * FROM {table_name}"
        
        # Apply CDC filter if high watermark exists
        high_watermark = self.get_high_watermark()
        if high_watermark:
            query = f"SELECT * FROM ({base_query}) sq WHERE CREATION_DATE > '{high_watermark}'"
            logger.info(f"CDC filter applied: CREATION_DATE > {high_watermark}")
        else:
            query = base_query
            logger.info("No high watermark found, processing all data")
        
        df = self.spark.read.jdbc(
            url=jdbc_url,
            table=f"({query}) AS source_data",
            properties=connection_props
        )
        
        # Select only configured columns
        selected_columns = [
            "C_ID",
            "DOC_DATE",
            "DOC_ID",
            "DOC_NO",
            "TP_SEQ_NO",
            "YEAR",
            "TOTAL_LAB_PRICE",
            "CREATION_DATE",
            "AMEND_LAST_DATE",
        ]
        
        df = df.select([col(c) for c in selected_columns])
        
        row_count = df.count()
        logger.info(f"Read {row_count} rows from source")
        return df
    
    def get_clickhouse_connection(self) -> tuple:
        """Get ClickHouse connection details."""
        target_url = os.getenv("CLICKHOUSE_URL", "jdbc:clickhouse://clickhouse:8123")
        target_host = os.getenv("CLICKHOUSE_HOST", "clickhouse")
        target_port = os.getenv("CLICKHOUSE_PORT", "8123")
        target_user = os.getenv("CLICKHOUSE_USER", "default")
        target_password = os.getenv("CLICKHOUSE_PASSWORD", "")
        return target_url, target_host, target_port, target_user, target_password
    
    def ensure_target_table_exists(self):
        """Create target table in ClickHouse if it doesn't exist using proper type mappings."""
        _, target_host, target_port, target_user, target_password = self.get_clickhouse_connection()
        target_table = f"{self.target_config['database']}.{self.target_config['table']}"
        
        # Build column definitions using mapped ClickHouse types
        column_defs = []
        column_defs.append("`C_ID` Float64")
        column_defs.append("`DOC_DATE` Nullable(DateTime)")
        column_defs.append("`DOC_ID` Float64")
        column_defs.append("`DOC_NO` String")
        column_defs.append("`TP_SEQ_NO` Float64")
        column_defs.append("`YEAR` Nullable(String)")
        column_defs.append("`TOTAL_LAB_PRICE` Nullable(Float64)")
        column_defs.append("`CREATION_DATE` Nullable(DateTime)")
        column_defs.append("`AMEND_LAST_DATE` Nullable(DateTime)")
        
        # Add metadata columns
        column_defs.extend([
            "`_novasight_app_id` String",
            "`_novasight_tenant_id` String",
            "`_novasight_loaded_at` DateTime64(6) DEFAULT now64()",
            "`_novasight_updated_at` Nullable(DateTime64(6))"
        ])
        
        columns_sql = ",\n    ".join(column_defs)
        
        # Build ORDER BY from primary keys
        order_by_cols = ", ".join([f"`{pk}`" for pk in self.primary_keys])
        
        # Use ReplacingMergeTree for SCD Type 1 (overwrites)
        create_sql = f"""
        CREATE TABLE IF NOT EXISTS {target_table} (
            {columns_sql}
        ) ENGINE = ReplacingMergeTree(_novasight_loaded_at)
        ORDER BY ({order_by_cols})
        PRIMARY KEY ({order_by_cols})
        """
        
        logger.info(f"Ensuring target table exists: {target_table}")
        logger.debug(f"Create table DDL:\n{create_sql}")
        
        try:
            # Use ClickHouse HTTP interface to execute DDL
            params = {"query": create_sql}
            if target_user:
                params["user"] = target_user
            if target_password:
                params["password"] = target_password
            
            query_string = urllib.parse.urlencode(params)
            http_url = f"http://{target_host}:{target_port}/?{query_string}"
            
            req = urllib.request.Request(http_url, method='POST')
            with urllib.request.urlopen(req, timeout=30) as response:
                if response.status == 200:
                    logger.info(f"Table {target_table} is ready")
                else:
                    logger.warning(f"Table creation response: {response.read().decode()}")
        except Exception as e:
            logger.warning(f"Could not create table via HTTP, will try JDBC: {e}")
    
    def read_target(self) -> DataFrame:
        """Read existing data from target for comparison."""
        target_url, _, _, target_user, target_password = self.get_clickhouse_connection()
        
        connection_props = {
            "user": target_user,
            "password": target_password,
            "driver": "com.clickhouse.jdbc.ClickHouseDriver",
        }
        
        target_table = f"{self.target_config['database']}.{self.target_config['table']}"
        
        try:
            # Read only primary key columns for matching
            pk_cols = ", ".join(self.primary_keys)
            query = f"SELECT {pk_cols} FROM {target_table}"
            
            return self.spark.read.jdbc(
                url=target_url,
                table=f"({query}) AS target_data",
                properties=connection_props
            )
        except Exception as e:
            logger.warning(f"Could not read target table: {e}")
            # Return empty DataFrame with PK schema
            from pyspark.sql.types import StructType
            return self.spark.createDataFrame([], StructType([]))
    
    def identify_changes(self, source_df: DataFrame, target_df: DataFrame) -> tuple:
        """
        Identify new and updated records.
        
        Returns:
            Tuple of (inserts_df, updates_df)
        """
        # Build join condition on primary keys
        join_condition = [source_df[pk] == target_df[pk] for pk in self.primary_keys]
        
        # Left join to find matches
        joined = source_df.join(
            target_df.select(self.primary_keys).withColumn("_exists", lit(True)),
            on=self.primary_keys,
            how="left"
        )
        
        # New records (no match in target)
        new_records = joined.filter(col("_exists").isNull()).drop("_exists")
        
        # Updated records (match in target)
        updated_records = joined.filter(col("_exists") == True).drop("_exists")
        
        logger.info(f"Identified {new_records.count()} new records and {updated_records.count()} updates")
        
        return new_records, updated_records
    
    def add_metadata_columns(self, df: DataFrame, is_update: bool = False) -> DataFrame:
        """Add metadata columns for audit tracking."""
        df = df \
            .withColumn("_novasight_app_id", lit(self.app_id)) \
            .withColumn("_novasight_tenant_id", lit("eb09c5fc-6c5b-4745-a7ea-c3166a65de97")) \
            .withColumn("_novasight_loaded_at", current_timestamp())
        
        if is_update:
            df = df.withColumn("_novasight_updated_at", current_timestamp())
        
        return df
    
    
    def write_to_target(self, inserts_df: DataFrame, updates_df: DataFrame):
        """Write data to ClickHouse target using ReplacingMergeTree."""
        logger.info(f"Writing to target: {self.target_config['database']}.{self.target_config['table']}")
        
        target_url, _, _, target_user, target_password = self.get_clickhouse_connection()
        
        connection_props = {
            "user": target_user,
            "password": target_password,
            "driver": "com.clickhouse.jdbc.ClickHouseDriver",
        }
        
        target_table = f"{self.target_config['database']}.{self.target_config['table']}"
        
        # Combine inserts and updates (SCD Type 1 - just upsert)
        # ReplacingMergeTree in ClickHouse handles the deduplication
        all_data = inserts_df.union(updates_df)
        
        
        all_data.write.jdbc(
            url=target_url,
            table=target_table,
            mode="append",  # ReplacingMergeTree handles duplicates
            properties=connection_props
        )
        
        total_rows = all_data.count()
        logger.info(f"Successfully wrote {total_rows} rows to target")
        
        return total_rows
    
    def run(self):
        """Execute the SCD Type 1 job."""
        logger.info(f"Starting SCD Type 1 job: {self.app_name}")
        start_time = datetime.now()
        
        try:
            # Ensure target table exists in ClickHouse
            self.ensure_target_table_exists()
            
            # Read source data
            source_df = self.read_source()
            
            if source_df.isEmpty():
                logger.info("No new data to process")
                return {
                    "status": "success",
                    "rows_processed": 0,
                    "rows_inserted": 0,
                    "rows_updated": 0,
                    "duration_seconds": 0,
                }
            
            # Read target for comparison
            target_df = self.read_target()
            
            # Identify changes
            inserts_df, updates_df = self.identify_changes(source_df, target_df)
            
            # Add metadata
            inserts_df = self.add_metadata_columns(inserts_df, is_update=False)
            updates_df = self.add_metadata_columns(updates_df, is_update=True)
            
            # Write to target
            total_written = self.write_to_target(inserts_df, updates_df)
            
            # Update high watermark
            max_watermark = source_df.agg({self.cdc_column: "max"}).collect()[0][0]
            if max_watermark:
                self.save_high_watermark(str(max_watermark))
            
            duration = (datetime.now() - start_time).total_seconds()
            logger.info(f"SCD Type 1 job completed in {duration:.2f} seconds")
            
            return {
                "status": "success",
                "rows_processed": source_df.count(),
                "rows_inserted": inserts_df.count(),
                "rows_updated": updates_df.count(),
                "duration_seconds": duration,
            }
            
        except Exception as e:
            logger.error(f"SCD Type 1 job failed: {str(e)}")
            raise


def main():
    """Main entry point."""
    spark = SparkSession.builder \
        .appName("extract_gl_data") \
        .config("spark.sql.adaptive.enabled", "true") \
        .config("spark.sql.adaptive.coalescePartitions.enabled", "true") \
        .config("spark.sql.shuffle.partitions", "200") \
        .getOrCreate()
    
    try:
        job = SCDType1Job(spark)
        result = job.run()
        logger.info(f"Job result: {result}")
    finally:
        spark.stop()


if __name__ == "__main__":
    main()
