"""initial_consolidated_schema

Revision ID: b078fbc26a17
Revises: 
Create Date: 2026-02-23 12:55:02.108930
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b078fbc26a17'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_category'), 'permissions', ['category'], unique=False)
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('infrastructure_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_system_default', sa.Boolean(), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('credential_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('last_test_at', sa.DateTime(), nullable=True),
    sa.Column('last_test_success', sa.Boolean(), nullable=True),
    sa.Column('last_test_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_infrastructure_configs_service_type'), 'infrastructure_configs', ['service_type'], unique=False)
    op.create_index(op.f('ix_infrastructure_configs_tenant_id'), 'infrastructure_configs', ['tenant_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('semantic_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('dbt_model', sa.String(length=100), nullable=False),
    sa.Column('model_type', sa.Enum('FACT', 'DIMENSION', 'AGGREGATE', name='modeltype'), nullable=False),
    sa.Column('target_schema', sa.String(length=100), nullable=True),
    sa.Column('target_table', sa.String(length=100), nullable=True),
    sa.Column('cache_enabled', sa.Boolean(), nullable=True),
    sa.Column('cache_ttl_seconds', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_semantic_model_tenant_name')
    )
    op.create_index(op.f('ix_semantic_models_tenant_id'), 'semantic_models', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('sso_provider', sa.String(length=50), nullable=True),
    sa.Column('sso_subject', sa.String(length=255), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_tenant_user_email')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('resource_name', sa.String(length=255), nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=True),
    sa.Column('entry_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_action', 'audit_logs', ['action', 'timestamp'], unique=False)
    op.create_index('idx_audit_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('idx_audit_severity', 'audit_logs', ['severity', 'timestamp'], unique=False)
    op.create_index('idx_audit_tenant_timestamp', 'audit_logs', ['tenant_id', 'timestamp'], unique=False)
    op.create_index('idx_audit_user_timestamp', 'audit_logs', ['user_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('chart_folders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['chart_folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chart_folders_name'), 'chart_folders', ['name'], unique=False)
    op.create_index(op.f('ix_chart_folders_parent_id'), 'chart_folders', ['parent_id'], unique=False)
    op.create_index(op.f('ix_chart_folders_tenant_id'), 'chart_folders', ['tenant_id'], unique=False)
    op.create_table('dag_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dag_id', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('schedule_type', sa.Enum('MANUAL', 'CRON', 'PRESET', name='scheduletype'), nullable=False),
    sa.Column('schedule_cron', sa.String(length=100), nullable=True),
    sa.Column('schedule_preset', sa.String(length=50), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('catchup', sa.Boolean(), nullable=False),
    sa.Column('max_active_runs', sa.Integer(), nullable=False),
    sa.Column('default_retries', sa.Integer(), nullable=False),
    sa.Column('default_retry_delay_minutes', sa.Integer(), nullable=False),
    sa.Column('notification_emails', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('email_on_failure', sa.Boolean(), nullable=False),
    sa.Column('email_on_success', sa.Boolean(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'ARCHIVED', 'ERROR', name='dagstatus'), nullable=False),
    sa.Column('deployed_at', sa.DateTime(), nullable=True),
    sa.Column('deployed_version', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'dag_id', name='uq_tenant_dag_id')
    )
    op.create_index(op.f('ix_dag_configs_dag_id'), 'dag_configs', ['dag_id'], unique=False)
    op.create_index(op.f('ix_dag_configs_tenant_id'), 'dag_configs', ['tenant_id'], unique=False)
    op.create_table('dashboards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('layout', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('shared_with', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('global_filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('auto_refresh', sa.Boolean(), nullable=False),
    sa.Column('refresh_interval', sa.Integer(), nullable=True),
    sa.Column('theme', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboards_name'), 'dashboards', ['name'], unique=False)
    op.create_index(op.f('ix_dashboards_tenant_id'), 'dashboards', ['tenant_id'], unique=False)
    op.create_table('data_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('db_type', sa.Enum('POSTGRESQL', 'ORACLE', 'SQLSERVER', 'MYSQL', 'CLICKHOUSE', name='databasetype'), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('database', sa.String(length=255), nullable=False),
    sa.Column('schema_name', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_encrypted', sa.Text(), nullable=False),
    sa.Column('ssl_mode', sa.String(length=50), nullable=True),
    sa.Column('ssl_cert', sa.Text(), nullable=True),
    sa.Column('extra_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ERROR', 'TESTING', name='connectionstatus'), nullable=False),
    sa.Column('last_tested_at', sa.DateTime(), nullable=True),
    sa.Column('last_test_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_tenant_connection_name')
    )
    op.create_index(op.f('ix_data_connections_tenant_id'), 'data_connections', ['tenant_id'], unique=False)
    op.create_table('dimensions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('semantic_model_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('CATEGORICAL', 'TEMPORAL', 'NUMERIC', 'HIERARCHICAL', name='dimensiontype'), nullable=False),
    sa.Column('expression', sa.String(length=500), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=True),
    sa.Column('is_primary_key', sa.Boolean(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=True),
    sa.Column('is_filterable', sa.Boolean(), nullable=True),
    sa.Column('is_groupable', sa.Boolean(), nullable=True),
    sa.Column('hierarchy_name', sa.String(length=100), nullable=True),
    sa.Column('hierarchy_level', sa.Integer(), nullable=True),
    sa.Column('parent_dimension_id', sa.UUID(), nullable=True),
    sa.Column('default_value', sa.String(length=100), nullable=True),
    sa.Column('format_string', sa.String(length=100), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_dimension_id'], ['dimensions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['semantic_model_id'], ['semantic_models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('semantic_model_id', 'name', name='uq_dimension_model_name')
    )
    op.create_index(op.f('ix_dimensions_tenant_id'), 'dimensions', ['tenant_id'], unique=False)
    op.create_table('measures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('semantic_model_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('aggregation', sa.Enum('SUM', 'COUNT', 'COUNT_DISTINCT', 'AVG', 'MIN', 'MAX', 'MEDIAN', 'PERCENTILE', 'STDDEV', 'VARIANCE', name='aggregationtype'), nullable=False),
    sa.Column('expression', sa.String(length=500), nullable=False),
    sa.Column('format', sa.String(length=50), nullable=True),
    sa.Column('format_string', sa.String(length=100), nullable=True),
    sa.Column('decimal_places', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('unit_suffix', sa.String(length=20), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=True),
    sa.Column('is_additive', sa.Boolean(), nullable=True),
    sa.Column('percentile_value', sa.Integer(), nullable=True),
    sa.Column('default_filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('time_dimension', sa.String(length=100), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['semantic_model_id'], ['semantic_models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('semantic_model_id', 'name', name='uq_measure_model_name')
    )
    op.create_index(op.f('ix_measures_tenant_id'), 'measures', ['tenant_id'], unique=False)
    op.create_table('resource_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('permission', sa.String(length=20), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=True),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'resource_type', 'resource_id', name='uq_user_resource_permission')
    )
    op.create_index(op.f('ix_resource_permissions_resource_id'), 'resource_permissions', ['resource_id'], unique=False)
    op.create_index(op.f('ix_resource_permissions_resource_type'), 'resource_permissions', ['resource_type'], unique=False)
    op.create_index(op.f('ix_resource_permissions_user_id'), 'resource_permissions', ['user_id'], unique=False)
    op.create_table('role_hierarchy',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_role_id', sa.UUID(), nullable=False),
    sa.Column('child_role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['child_role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_role_id', 'child_role_id', name='uq_role_hierarchy')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('semantic_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_model_id', sa.UUID(), nullable=False),
    sa.Column('to_model_id', sa.UUID(), nullable=False),
    sa.Column('from_column', sa.String(length=100), nullable=False),
    sa.Column('to_column', sa.String(length=100), nullable=False),
    sa.Column('relationship_type', sa.Enum('ONE_TO_ONE', 'ONE_TO_MANY', 'MANY_TO_ONE', name='relationshiptype'), nullable=False),
    sa.Column('join_type', sa.String(length=20), nullable=True),
    sa.Column('additional_conditions', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['from_model_id'], ['semantic_models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_model_id'], ['semantic_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semantic_relationships_tenant_id'), 'semantic_relationships', ['tenant_id'], unique=False)
    op.create_table('user_role_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('charts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('chart_type', sa.Enum('BAR', 'LINE', 'PIE', 'AREA', 'SCATTER', 'DONUT', 'METRIC', 'TABLE', 'HEATMAP', 'GAUGE', 'TREEMAP', 'FUNNEL', name='charttype'), nullable=False),
    sa.Column('source_type', sa.Enum('SEMANTIC_MODEL', 'SQL_QUERY', name='chartsourcetype'), nullable=False),
    sa.Column('semantic_model_id', sa.UUID(), nullable=True),
    sa.Column('sql_query', sa.Text(), nullable=True),
    sa.Column('query_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('viz_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('folder_id', sa.UUID(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('cached_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cache_expires_at', sa.DateTime(), nullable=True),
    sa.Column('cache_ttl_seconds', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['folder_id'], ['chart_folders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['semantic_model_id'], ['semantic_models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_charts_folder_id'), 'charts', ['folder_id'], unique=False)
    op.create_index(op.f('ix_charts_name'), 'charts', ['name'], unique=False)
    op.create_index(op.f('ix_charts_semantic_model_id'), 'charts', ['semantic_model_id'], unique=False)
    op.create_index(op.f('ix_charts_tenant_id'), 'charts', ['tenant_id'], unique=False)
    op.create_table('dag_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dag_config_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dag_file_content', sa.Text(), nullable=True),
    sa.Column('change_description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dag_config_id'], ['dag_configs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dag_config_id', 'version', name='uq_dag_version')
    )
    op.create_index(op.f('ix_dag_versions_dag_config_id'), 'dag_versions', ['dag_config_id'], unique=False)
    op.create_table('pyspark_apps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'INACTIVE', 'ERROR', name='pysparkappstatus'), nullable=False),
    sa.Column('source_type', sa.Enum('TABLE', 'QUERY', name='sourcetype'), nullable=False),
    sa.Column('source_schema', sa.String(length=255), nullable=True),
    sa.Column('source_table', sa.String(length=255), nullable=True),
    sa.Column('source_query', sa.Text(), nullable=True),
    sa.Column('columns_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('primary_key_columns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cdc_type', sa.Enum('NONE', 'TIMESTAMP', 'VERSION', 'HASH', name='cdctype'), nullable=False),
    sa.Column('cdc_column', sa.String(length=255), nullable=True),
    sa.Column('cdc_high_watermark', sa.Text(), nullable=True),
    sa.Column('partition_columns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scd_type', sa.Enum('NONE', 'TYPE1', 'TYPE2', name='scdtype'), nullable=False),
    sa.Column('write_mode', sa.Enum('APPEND', 'OVERWRITE', 'MERGE', name='writemode'), nullable=False),
    sa.Column('target_database', sa.String(length=255), nullable=True),
    sa.Column('target_table', sa.String(length=255), nullable=True),
    sa.Column('target_engine', sa.String(length=100), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_code', sa.Text(), nullable=True),
    sa.Column('generated_code_hash', sa.String(length=64), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('template_version', sa.String(length=50), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_status', sa.String(length=50), nullable=True),
    sa.Column('last_run_rows', sa.Integer(), nullable=True),
    sa.Column('last_run_duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['data_connections.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_tenant_pyspark_app_name')
    )
    op.create_index(op.f('ix_pyspark_apps_connection_id'), 'pyspark_apps', ['connection_id'], unique=False)
    op.create_index(op.f('ix_pyspark_apps_tenant_id'), 'pyspark_apps', ['tenant_id'], unique=False)
    op.create_table('saved_queries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sql', sa.Text(), nullable=False),
    sa.Column('query_type', sa.Enum('ADHOC', 'PYSPARK', 'DBT', 'REPORT', name='querytype'), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=True),
    sa.Column('is_clickhouse', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['data_connections.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_tenant_savedquery_name')
    )
    op.create_index(op.f('ix_saved_queries_tenant_id'), 'saved_queries', ['tenant_id'], unique=False)
    op.create_table('task_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dag_config_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('task_type', sa.Enum('SPARK_SUBMIT', 'DBT_RUN', 'DBT_TEST', 'SQL_QUERY', 'EMAIL', 'HTTP_SENSOR', 'TIME_SENSOR', 'PYTHON_OPERATOR', 'BASH_OPERATOR', name='tasktype'), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timeout_minutes', sa.Integer(), nullable=False),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('retry_delay_minutes', sa.Integer(), nullable=False),
    sa.Column('trigger_rule', sa.Enum('ALL_SUCCESS', 'ALL_FAILED', 'ALL_DONE', 'ONE_SUCCESS', 'ONE_FAILED', 'NONE_FAILED', 'NONE_SKIPPED', name='triggerrule'), nullable=False),
    sa.Column('depends_on', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('position_x', sa.Integer(), nullable=False),
    sa.Column('position_y', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dag_config_id'], ['dag_configs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dag_config_id', 'task_id', name='uq_dag_task_id')
    )
    op.create_index(op.f('ix_task_configs_dag_config_id'), 'task_configs', ['dag_config_id'], unique=False)
    op.create_table('widgets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dashboard_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('BAR_CHART', 'LINE_CHART', 'PIE_CHART', 'TABLE', 'METRIC_CARD', 'AREA_CHART', 'SCATTER_PLOT', 'HEATMAP', 'DONUT_CHART', 'GAUGE', 'TREEMAP', 'FUNNEL', 'TEXT', name='widgettype'), nullable=False),
    sa.Column('query_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('viz_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('grid_position', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cached_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cache_expires_at', sa.DateTime(), nullable=True),
    sa.Column('local_filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('drilldown_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_widgets_dashboard_id'), 'widgets', ['dashboard_id'], unique=False)
    op.create_index(op.f('ix_widgets_tenant_id'), 'widgets', ['tenant_id'], unique=False)
    op.create_table('dashboard_charts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dashboard_id', sa.UUID(), nullable=False),
    sa.Column('chart_id', sa.UUID(), nullable=False),
    sa.Column('grid_position', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('local_filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('local_viz_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chart_id'], ['charts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dashboard_id', 'chart_id', name='uq_dashboard_chart')
    )
    op.create_index(op.f('ix_dashboard_charts_chart_id'), 'dashboard_charts', ['chart_id'], unique=False)
    op.create_index(op.f('ix_dashboard_charts_dashboard_id'), 'dashboard_charts', ['dashboard_id'], unique=False)
    op.create_index(op.f('ix_dashboard_charts_tenant_id'), 'dashboard_charts', ['tenant_id'], unique=False)
    # NOTE: Removed auto-generated 'op.drop_table("alembic_version")' — must never drop Alembic's own tracking table!
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dashboard_charts_tenant_id'), table_name='dashboard_charts')
    op.drop_index(op.f('ix_dashboard_charts_dashboard_id'), table_name='dashboard_charts')
    op.drop_index(op.f('ix_dashboard_charts_chart_id'), table_name='dashboard_charts')
    op.drop_table('dashboard_charts')
    op.drop_index(op.f('ix_widgets_tenant_id'), table_name='widgets')
    op.drop_index(op.f('ix_widgets_dashboard_id'), table_name='widgets')
    op.drop_table('widgets')
    op.drop_index(op.f('ix_task_configs_dag_config_id'), table_name='task_configs')
    op.drop_table('task_configs')
    op.drop_index(op.f('ix_saved_queries_tenant_id'), table_name='saved_queries')
    op.drop_table('saved_queries')
    op.drop_index(op.f('ix_pyspark_apps_tenant_id'), table_name='pyspark_apps')
    op.drop_index(op.f('ix_pyspark_apps_connection_id'), table_name='pyspark_apps')
    op.drop_table('pyspark_apps')
    op.drop_index(op.f('ix_dag_versions_dag_config_id'), table_name='dag_versions')
    op.drop_table('dag_versions')
    op.drop_index(op.f('ix_charts_tenant_id'), table_name='charts')
    op.drop_index(op.f('ix_charts_semantic_model_id'), table_name='charts')
    op.drop_index(op.f('ix_charts_name'), table_name='charts')
    op.drop_index(op.f('ix_charts_folder_id'), table_name='charts')
    op.drop_table('charts')
    op.drop_table('user_roles')
    op.drop_table('user_role_assignments')
    op.drop_index(op.f('ix_semantic_relationships_tenant_id'), table_name='semantic_relationships')
    op.drop_table('semantic_relationships')
    op.drop_table('role_permissions')
    op.drop_table('role_hierarchy')
    op.drop_index(op.f('ix_resource_permissions_user_id'), table_name='resource_permissions')
    op.drop_index(op.f('ix_resource_permissions_resource_type'), table_name='resource_permissions')
    op.drop_index(op.f('ix_resource_permissions_resource_id'), table_name='resource_permissions')
    op.drop_table('resource_permissions')
    op.drop_index(op.f('ix_measures_tenant_id'), table_name='measures')
    op.drop_table('measures')
    op.drop_index(op.f('ix_dimensions_tenant_id'), table_name='dimensions')
    op.drop_table('dimensions')
    op.drop_index(op.f('ix_data_connections_tenant_id'), table_name='data_connections')
    op.drop_table('data_connections')
    op.drop_index(op.f('ix_dashboards_tenant_id'), table_name='dashboards')
    op.drop_index(op.f('ix_dashboards_name'), table_name='dashboards')
    op.drop_table('dashboards')
    op.drop_index(op.f('ix_dag_configs_tenant_id'), table_name='dag_configs')
    op.drop_index(op.f('ix_dag_configs_dag_id'), table_name='dag_configs')
    op.drop_table('dag_configs')
    op.drop_index(op.f('ix_chart_folders_tenant_id'), table_name='chart_folders')
    op.drop_index(op.f('ix_chart_folders_parent_id'), table_name='chart_folders')
    op.drop_index(op.f('ix_chart_folders_name'), table_name='chart_folders')
    op.drop_table('chart_folders')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('idx_audit_user_timestamp', table_name='audit_logs')
    op.drop_index('idx_audit_tenant_timestamp', table_name='audit_logs')
    op.drop_index('idx_audit_severity', table_name='audit_logs')
    op.drop_index('idx_audit_resource', table_name='audit_logs')
    op.drop_index('idx_audit_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_semantic_models_tenant_id'), table_name='semantic_models')
    op.drop_table('semantic_models')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_infrastructure_configs_tenant_id'), table_name='infrastructure_configs')
    op.drop_index(op.f('ix_infrastructure_configs_service_type'), table_name='infrastructure_configs')
    op.drop_table('infrastructure_configs')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_category'), table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
