"""dlt_pipelines.connection_id FK ON DELETE CASCADE

Revision ID: b9d2e3f4a5c6
Revises: a8c1d4e6f7b2
Create Date: 2026-04-27 09:30:00.000000

When a DataConnection is deleted, its dlt_pipelines must be deleted too.
The original FK had no ON DELETE action, which caused SQLAlchemy's ORM
backref to attempt setting connection_id NULL (NOT NULL violation).
"""
from alembic import op


revision = "b9d2e3f4a5c6"
down_revision = "a8c1d4e6f7b2"
branch_labels = None
depends_on = None


# Constraint name as generated by Postgres for the original FK.
_OLD_FK = "dlt_pipelines_connection_id_fkey"
_NEW_FK = "dlt_pipelines_connection_id_fkey"


def upgrade() -> None:
    op.drop_constraint(_OLD_FK, "dlt_pipelines", type_="foreignkey")
    op.create_foreign_key(
        _NEW_FK,
        "dlt_pipelines",
        "data_connections",
        ["connection_id"],
        ["id"],
        ondelete="CASCADE",
    )


def downgrade() -> None:
    op.drop_constraint(_NEW_FK, "dlt_pipelines", type_="foreignkey")
    op.create_foreign_key(
        _OLD_FK,
        "dlt_pipelines",
        "data_connections",
        ["connection_id"],
        ["id"],
    )
