"""sync_models_with_database

Revision ID: 53a2e62b06e9
Revises: 006
Create Date: 2026-02-07 13:37:32.322361+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53a2e62b06e9'
down_revision: Union[str, None] = '006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: permissions already created by 005_add_rbac_tables
    # NOTE: infrastructure_configs already created by 006_add_infrastructure_configs
    op.create_table('semantic_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('dbt_model', sa.String(length=100), nullable=False),
    sa.Column('model_type', sa.Enum('FACT', 'DIMENSION', 'AGGREGATE', name='modeltype'), nullable=False),
    sa.Column('target_schema', sa.String(length=100), nullable=True),
    sa.Column('target_table', sa.String(length=100), nullable=True),
    sa.Column('cache_enabled', sa.Boolean(), nullable=True),
    sa.Column('cache_ttl_seconds', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_semantic_model_tenant_name')
    )
    op.create_index(op.f('ix_semantic_models_tenant_id'), 'semantic_models', ['tenant_id'], unique=False)
    # NOTE: dashboards already created by 003_add_dashboards
    op.create_table('dimensions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('semantic_model_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('CATEGORICAL', 'TEMPORAL', 'NUMERIC', 'HIERARCHICAL', name='dimensiontype'), nullable=False),
    sa.Column('expression', sa.String(length=500), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=True),
    sa.Column('is_primary_key', sa.Boolean(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=True),
    sa.Column('is_filterable', sa.Boolean(), nullable=True),
    sa.Column('is_groupable', sa.Boolean(), nullable=True),
    sa.Column('hierarchy_name', sa.String(length=100), nullable=True),
    sa.Column('hierarchy_level', sa.Integer(), nullable=True),
    sa.Column('parent_dimension_id', sa.UUID(), nullable=True),
    sa.Column('default_value', sa.String(length=100), nullable=True),
    sa.Column('format_string', sa.String(length=100), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_dimension_id'], ['dimensions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['semantic_model_id'], ['semantic_models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('semantic_model_id', 'name', name='uq_dimension_model_name')
    )
    op.create_index(op.f('ix_dimensions_tenant_id'), 'dimensions', ['tenant_id'], unique=False)
    op.create_table('measures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('semantic_model_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('aggregation', sa.Enum('SUM', 'COUNT', 'COUNT_DISTINCT', 'AVG', 'MIN', 'MAX', 'MEDIAN', 'PERCENTILE', 'STDDEV', 'VARIANCE', name='aggregationtype'), nullable=False),
    sa.Column('expression', sa.String(length=500), nullable=False),
    sa.Column('format', sa.String(length=50), nullable=True),
    sa.Column('format_string', sa.String(length=100), nullable=True),
    sa.Column('decimal_places', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('unit_suffix', sa.String(length=20), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=True),
    sa.Column('is_additive', sa.Boolean(), nullable=True),
    sa.Column('percentile_value', sa.Integer(), nullable=True),
    sa.Column('default_filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('time_dimension', sa.String(length=100), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['semantic_model_id'], ['semantic_models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('semantic_model_id', 'name', name='uq_measure_model_name')
    )
    op.create_index(op.f('ix_measures_tenant_id'), 'measures', ['tenant_id'], unique=False)
    # NOTE: resource_permissions, role_hierarchy, role_permissions already created by 005_add_rbac_tables
    op.create_table('semantic_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_model_id', sa.UUID(), nullable=False),
    sa.Column('to_model_id', sa.UUID(), nullable=False),
    sa.Column('from_column', sa.String(length=100), nullable=False),
    sa.Column('to_column', sa.String(length=100), nullable=False),
    sa.Column('relationship_type', sa.Enum('ONE_TO_ONE', 'ONE_TO_MANY', 'MANY_TO_ONE', name='relationshiptype'), nullable=False),
    sa.Column('join_type', sa.String(length=20), nullable=True),
    sa.Column('additional_conditions', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['from_model_id'], ['semantic_models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_model_id'], ['semantic_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semantic_relationships_tenant_id'), 'semantic_relationships', ['tenant_id'], unique=False)
    # NOTE: user_role_assignments - truly new table
    op.create_table('user_role_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role')
    )
    # NOTE: pyspark_apps already created by 002_add_pyspark_apps
    # NOTE: widgets already created by 003_add_dashboards
    # Drop platform_audit_log and platform_admins only if they exist
    # (platform_audit_log was never created by migrations, only by db.create_all())
    op.execute("DROP INDEX IF EXISTS idx_platform_audit_created")
    op.execute("DROP TABLE IF EXISTS platform_audit_log")
    op.execute("DROP TABLE IF EXISTS platform_admins")
    op.add_column('audit_logs', sa.Column('timestamp', sa.DateTime(), nullable=False))
    op.add_column('audit_logs', sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('audit_logs', sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('audit_logs', sa.Column('severity', sa.String(length=20), nullable=False))
    op.add_column('audit_logs', sa.Column('previous_hash', sa.String(length=64), nullable=True))
    op.add_column('audit_logs', sa.Column('entry_hash', sa.String(length=64), nullable=False))
    op.alter_column('audit_logs', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('audit_logs', 'resource_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('audit_logs', 'resource_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True,
               postgresql_using='resource_id::uuid')
    op.alter_column('audit_logs', 'user_agent',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('audit_logs', 'success',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('idx_audit_logs_action', table_name='audit_logs')
    op.drop_index('idx_audit_logs_created', table_name='audit_logs')
    op.drop_index('idx_audit_logs_tenant', table_name='audit_logs')
    op.drop_index('idx_audit_logs_user', table_name='audit_logs')
    op.create_index('idx_audit_action', 'audit_logs', ['action', 'timestamp'], unique=False)
    op.create_index('idx_audit_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('idx_audit_severity', 'audit_logs', ['severity', 'timestamp'], unique=False)
    op.create_index('idx_audit_tenant_timestamp', 'audit_logs', ['tenant_id', 'timestamp'], unique=False)
    op.create_index('idx_audit_user_timestamp', 'audit_logs', ['user_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.drop_column('audit_logs', 'old_values')
    op.drop_column('audit_logs', 'new_values')
    op.drop_column('audit_logs', 'created_at')
    op.alter_column('dag_configs', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('dag_configs', 'current_version',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    sa.Enum('MANUAL', 'CRON', 'PRESET', name='scheduletype').create(op.get_bind(), checkfirst=True)
    op.alter_column('dag_configs', 'schedule_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('dag_configs', 'schedule_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('MANUAL', 'CRON', 'PRESET', name='scheduletype'),
               existing_nullable=False,
               postgresql_using='schedule_type::scheduletype')
    op.alter_column('dag_configs', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('dag_configs', 'start_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('dag_configs', 'catchup',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('dag_configs', 'max_active_runs',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('dag_configs', 'default_retries',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('dag_configs', 'default_retry_delay_minutes',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('dag_configs', 'notification_emails',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               server_default=None,
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=False)
    op.alter_column('dag_configs', 'email_on_failure',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('dag_configs', 'email_on_success',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('dag_configs', 'tags',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               server_default=None,
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=False)
    sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'ARCHIVED', 'ERROR', name='dagstatus').create(op.get_bind(), checkfirst=True)
    op.alter_column('dag_configs', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('dag_configs', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'ARCHIVED', 'ERROR', name='dagstatus'),
               existing_nullable=False,
               postgresql_using='status::dagstatus')
    op.alter_column('dag_configs', 'deployed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('dag_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('dag_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False)
    op.drop_index('idx_dag_configs_status', table_name='dag_configs')
    op.drop_index('idx_dag_configs_tenant', table_name='dag_configs')
    op.create_index(op.f('ix_dag_configs_dag_id'), 'dag_configs', ['dag_id'], unique=False)
    op.create_index(op.f('ix_dag_configs_tenant_id'), 'dag_configs', ['tenant_id'], unique=False)
    op.drop_constraint('dag_configs_tenant_id_fkey', 'dag_configs', type_='foreignkey')
    op.create_foreign_key(None, 'dag_configs', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('dag_versions', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('dag_versions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False)
    op.drop_index('idx_dag_versions_config', table_name='dag_versions')
    op.create_index(op.f('ix_dag_versions_dag_config_id'), 'dag_versions', ['dag_config_id'], unique=False)
    op.drop_constraint('dag_versions_dag_config_id_fkey', 'dag_versions', type_='foreignkey')
    op.create_foreign_key(None, 'dag_versions', 'dag_configs', ['dag_config_id'], ['id'])
    op.alter_column('data_connections', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    sa.Enum('POSTGRESQL', 'ORACLE', 'SQLSERVER', 'MYSQL', 'CLICKHOUSE', name='databasetype').create(op.get_bind(), checkfirst=True)
    op.alter_column('data_connections', 'db_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('POSTGRESQL', 'ORACLE', 'SQLSERVER', 'MYSQL', 'CLICKHOUSE', name='databasetype'),
               existing_nullable=False,
               postgresql_using='db_type::databasetype')
    op.alter_column('data_connections', 'extra_params',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    sa.Enum('ACTIVE', 'INACTIVE', 'ERROR', 'TESTING', name='connectionstatus').create(op.get_bind(), checkfirst=True)
    op.alter_column('data_connections', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('data_connections', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('ACTIVE', 'INACTIVE', 'ERROR', 'TESTING', name='connectionstatus'),
               existing_nullable=False,
               postgresql_using='status::connectionstatus')
    op.alter_column('data_connections', 'last_tested_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('data_connections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('data_connections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False)
    op.drop_index('idx_connections_tenant', table_name='data_connections')
    op.create_index(op.f('ix_data_connections_tenant_id'), 'data_connections', ['tenant_id'], unique=False)
    op.drop_constraint('data_connections_tenant_id_fkey', 'data_connections', type_='foreignkey')
    op.create_foreign_key(None, 'data_connections', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('roles', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('roles', 'permissions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('roles', 'is_system',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('roles', 'is_default',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('roles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False)
    op.drop_index('idx_roles_name', table_name='roles')
    op.drop_constraint('roles_name_key', 'roles', type_='unique')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.alter_column('task_configs', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    sa.Enum('SPARK_SUBMIT', 'DBT_RUN', 'DBT_TEST', 'SQL_QUERY', 'EMAIL', 'HTTP_SENSOR', 'TIME_SENSOR', 'PYTHON_OPERATOR', 'BASH_OPERATOR', name='tasktype').create(op.get_bind(), checkfirst=True)
    op.alter_column('task_configs', 'task_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('SPARK_SUBMIT', 'DBT_RUN', 'DBT_TEST', 'SQL_QUERY', 'EMAIL', 'HTTP_SENSOR', 'TIME_SENSOR', 'PYTHON_OPERATOR', 'BASH_OPERATOR', name='tasktype'),
               existing_nullable=False,
               postgresql_using='task_type::tasktype')
    op.alter_column('task_configs', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('task_configs', 'timeout_minutes',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('task_configs', 'retries',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('task_configs', 'retry_delay_minutes',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    sa.Enum('ALL_SUCCESS', 'ALL_FAILED', 'ALL_DONE', 'ONE_SUCCESS', 'ONE_FAILED', 'NONE_FAILED', 'NONE_SKIPPED', name='triggerrule').create(op.get_bind(), checkfirst=True)
    op.alter_column('task_configs', 'trigger_rule',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('task_configs', 'trigger_rule',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('ALL_SUCCESS', 'ALL_FAILED', 'ALL_DONE', 'ONE_SUCCESS', 'ONE_FAILED', 'NONE_FAILED', 'NONE_SKIPPED', name='triggerrule'),
               existing_nullable=False,
               postgresql_using='trigger_rule::triggerrule')
    op.alter_column('task_configs', 'depends_on',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               server_default=None,
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=False)
    op.alter_column('task_configs', 'position_x',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('task_configs', 'position_y',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('idx_task_configs_dag', table_name='task_configs')
    op.create_index(op.f('ix_task_configs_dag_config_id'), 'task_configs', ['dag_config_id'], unique=False)
    op.drop_constraint('task_configs_dag_config_id_fkey', 'task_configs', type_='foreignkey')
    op.create_foreign_key(None, 'task_configs', 'dag_configs', ['dag_config_id'], ['id'])
    op.alter_column('tenants', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tenants', 'plan',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tenants', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tenants', 'settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tenants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('tenants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False)
    op.drop_index('idx_tenants_slug', table_name='tenants')
    op.drop_index('idx_tenants_status', table_name='tenants')
    op.drop_constraint('tenants_slug_key', 'tenants', type_='unique')
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.alter_column('user_roles', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_constraint('user_roles_user_id_fkey', 'user_roles', type_='foreignkey')
    op.drop_constraint('user_roles_role_id_fkey', 'user_roles', type_='foreignkey')
    op.drop_constraint('user_roles_assigned_by_fkey', 'user_roles', type_='foreignkey')
    op.create_foreign_key(None, 'user_roles', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_roles', 'roles', ['role_id'], ['id'])
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'preferences',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('users', 'last_login_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_status', table_name='users')
    op.drop_index('idx_users_tenant', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.drop_constraint('users_tenant_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_tenant_id_fkey', 'users', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('idx_users_tenant', 'users', ['tenant_id'], unique=False)
    op.create_index('idx_users_status', 'users', ['status'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.alter_column('users', 'last_login_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('users', 'preferences',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'active'::character varying"),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.create_foreign_key('user_roles_assigned_by_fkey', 'user_roles', 'users', ['assigned_by'], ['id'])
    op.create_foreign_key('user_roles_role_id_fkey', 'user_roles', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('user_roles_user_id_fkey', 'user_roles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_roles', 'assigned_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.create_unique_constraint('tenants_slug_key', 'tenants', ['slug'], postgresql_nulls_not_distinct=False)
    op.create_index('idx_tenants_status', 'tenants', ['status'], unique=False)
    op.create_index('idx_tenants_slug', 'tenants', ['slug'], unique=False)
    op.alter_column('tenants', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('tenants', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('tenants', 'settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.alter_column('tenants', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'active'::character varying"),
               existing_nullable=False)
    op.alter_column('tenants', 'plan',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'basic'::character varying"),
               existing_nullable=False)
    op.alter_column('tenants', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.drop_constraint(None, 'task_configs', type_='foreignkey')
    op.create_foreign_key('task_configs_dag_config_id_fkey', 'task_configs', 'dag_configs', ['dag_config_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_task_configs_dag_config_id'), table_name='task_configs')
    op.create_index('idx_task_configs_dag', 'task_configs', ['dag_config_id'], unique=False)
    op.alter_column('task_configs', 'position_y',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('task_configs', 'position_x',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('task_configs', 'depends_on',
               existing_type=postgresql.ARRAY(sa.String()),
               server_default=sa.text("'{}'::text[]"),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=False)
    op.alter_column('task_configs', 'trigger_rule',
               existing_type=sa.Enum('ALL_SUCCESS', 'ALL_FAILED', 'ALL_DONE', 'ONE_SUCCESS', 'ONE_FAILED', 'NONE_FAILED', 'NONE_SKIPPED', name='triggerrule'),
               server_default=sa.text("'all_success'::character varying"),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('task_configs', 'retry_delay_minutes',
               existing_type=sa.INTEGER(),
               server_default=sa.text('5'),
               existing_nullable=False)
    op.alter_column('task_configs', 'retries',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('task_configs', 'timeout_minutes',
               existing_type=sa.INTEGER(),
               server_default=sa.text('60'),
               existing_nullable=False)
    op.alter_column('task_configs', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.alter_column('task_configs', 'task_type',
               existing_type=sa.Enum('SPARK_SUBMIT', 'DBT_RUN', 'DBT_TEST', 'SQL_QUERY', 'EMAIL', 'HTTP_SENSOR', 'TIME_SENSOR', 'PYTHON_OPERATOR', 'BASH_OPERATOR', name='tasktype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('task_configs', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_unique_constraint('roles_name_key', 'roles', ['name'], postgresql_nulls_not_distinct=False)
    op.create_index('idx_roles_name', 'roles', ['name'], unique=False)
    op.alter_column('roles', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('roles', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('roles', 'is_default',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=True)
    op.alter_column('roles', 'is_system',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=True)
    op.alter_column('roles', 'permissions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.alter_column('roles', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.drop_constraint(None, 'data_connections', type_='foreignkey')
    op.create_foreign_key('data_connections_tenant_id_fkey', 'data_connections', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_data_connections_tenant_id'), table_name='data_connections')
    op.create_index('idx_connections_tenant', 'data_connections', ['tenant_id'], unique=False)
    op.alter_column('data_connections', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('data_connections', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('data_connections', 'last_tested_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('data_connections', 'status',
               existing_type=sa.Enum('ACTIVE', 'INACTIVE', 'ERROR', 'TESTING', name='connectionstatus'),
               server_default=sa.text("'active'::character varying"),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('data_connections', 'extra_params',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.alter_column('data_connections', 'db_type',
               existing_type=sa.Enum('POSTGRESQL', 'ORACLE', 'SQLSERVER', 'MYSQL', 'CLICKHOUSE', name='databasetype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('data_connections', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.drop_constraint(None, 'dag_versions', type_='foreignkey')
    op.create_foreign_key('dag_versions_dag_config_id_fkey', 'dag_versions', 'dag_configs', ['dag_config_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_dag_versions_dag_config_id'), table_name='dag_versions')
    op.create_index('idx_dag_versions_config', 'dag_versions', ['dag_config_id'], unique=False)
    op.alter_column('dag_versions', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('dag_versions', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.drop_constraint(None, 'dag_configs', type_='foreignkey')
    op.create_foreign_key('dag_configs_tenant_id_fkey', 'dag_configs', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_dag_configs_tenant_id'), table_name='dag_configs')
    op.drop_index(op.f('ix_dag_configs_dag_id'), table_name='dag_configs')
    op.create_index('idx_dag_configs_tenant', 'dag_configs', ['tenant_id'], unique=False)
    op.create_index('idx_dag_configs_status', 'dag_configs', ['status'], unique=False)
    op.alter_column('dag_configs', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('dag_configs', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('dag_configs', 'deployed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('dag_configs', 'status',
               existing_type=sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'ARCHIVED', 'ERROR', name='dagstatus'),
               server_default=sa.text("'draft'::character varying"),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('dag_configs', 'tags',
               existing_type=postgresql.ARRAY(sa.String()),
               server_default=sa.text("'{}'::text[]"),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=False)
    op.alter_column('dag_configs', 'email_on_success',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('dag_configs', 'email_on_failure',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('dag_configs', 'notification_emails',
               existing_type=postgresql.ARRAY(sa.String()),
               server_default=sa.text("'{}'::text[]"),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=False)
    op.alter_column('dag_configs', 'default_retry_delay_minutes',
               existing_type=sa.INTEGER(),
               server_default=sa.text('5'),
               existing_nullable=False)
    op.alter_column('dag_configs', 'default_retries',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('dag_configs', 'max_active_runs',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('dag_configs', 'catchup',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('dag_configs', 'start_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('dag_configs', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'UTC'::character varying"),
               existing_nullable=False)
    op.alter_column('dag_configs', 'schedule_type',
               existing_type=sa.Enum('MANUAL', 'CRON', 'PRESET', name='scheduletype'),
               server_default=sa.text("'manual'::character varying"),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('dag_configs', 'current_version',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('dag_configs', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.add_column('audit_logs', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('idx_audit_user_timestamp', table_name='audit_logs')
    op.drop_index('idx_audit_tenant_timestamp', table_name='audit_logs')
    op.drop_index('idx_audit_severity', table_name='audit_logs')
    op.drop_index('idx_audit_resource', table_name='audit_logs')
    op.drop_index('idx_audit_action', table_name='audit_logs')
    op.create_index('idx_audit_logs_user', 'audit_logs', ['user_id'], unique=False)
    op.create_index('idx_audit_logs_tenant', 'audit_logs', ['tenant_id'], unique=False)
    op.create_index('idx_audit_logs_created', 'audit_logs', [sa.text('created_at DESC')], unique=False)
    op.create_index('idx_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.alter_column('audit_logs', 'success',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('audit_logs', 'user_agent',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'resource_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('audit_logs', 'resource_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('audit_logs', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.drop_column('audit_logs', 'entry_hash')
    op.drop_column('audit_logs', 'previous_hash')
    op.drop_column('audit_logs', 'severity')
    op.drop_column('audit_logs', 'extra_data')
    op.drop_column('audit_logs', 'changes')
    op.drop_column('audit_logs', 'timestamp')
    op.create_table('platform_admins',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='platform_admins_pkey'),
    sa.UniqueConstraint('email', name='platform_admins_email_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('platform_audit_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('admin_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('resource_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['platform_admins.id'], name='platform_audit_log_admin_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='platform_audit_log_pkey')
    )
    op.create_index('idx_platform_audit_created', 'platform_audit_log', [sa.text('created_at DESC')], unique=False)
    # NOTE: Only drop tables that THIS migration created (the 5 new ones)
    # Tables owned by 002, 003, 005, 006 are NOT dropped here
    op.drop_table('user_role_assignments')
    op.drop_index(op.f('ix_semantic_relationships_tenant_id'), table_name='semantic_relationships')
    op.drop_table('semantic_relationships')
    op.drop_index(op.f('ix_measures_tenant_id'), table_name='measures')
    op.drop_table('measures')
    op.drop_index(op.f('ix_dimensions_tenant_id'), table_name='dimensions')
    op.drop_table('dimensions')
    op.drop_index(op.f('ix_semantic_models_tenant_id'), table_name='semantic_models')
    op.drop_table('semantic_models')
    # ### end Alembic commands ###
