"""add_saved_queries_table

Revision ID: b5400357036d
Revises: 53a2e62b06e9
Create Date: 2026-02-11 11:33:36.459761
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5400357036d'
down_revision: Union[str, None] = '53a2e62b06e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_queries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sql', sa.Text(), nullable=False),
    sa.Column('query_type', sa.Enum('ADHOC', 'PYSPARK', 'DBT', 'REPORT', name='querytype'), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=True),
    sa.Column('is_clickhouse', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['data_connections.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_tenant_savedquery_name')
    )
    op.create_index(op.f('ix_saved_queries_tenant_id'), 'saved_queries', ['tenant_id'], unique=False)
    # NOTE: Removed auto-generated garbage:
    # - platform_audit_log/platform_admins already dropped by 53a2e62b06e9
    # - _metadata tables are dev-environment artifacts
    # - alembic_version must NEVER be dropped
    # - FK changes on dag_configs/data_connections already done by 53a2e62b06e9
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: Removed auto-generated garbage from downgrade:
    # - FK constraint changes (already handled by 53a2e62b06e9 downgrade)
    # - _metadata tables (dev-environment artifacts)
    # - alembic_version (must never be touched)
    # - platform_admins/platform_audit_log (handled by 53a2e62b06e9 downgrade)
    op.drop_index(op.f('ix_saved_queries_tenant_id'), table_name='saved_queries')
    op.drop_table('saved_queries')
    # ### end Alembic commands ###
